# Generated by Django 2.1.15 on 2020-04-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yiqiping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
